# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c2b7be89d13e8e2395f147edaa734b84e46ea858814bafab57232b4eeb032ca811758da3c74e9225aba01ce2319fe2a57bef9abe3ba8e652a78cac3ebef2f4

test:
  secret_key_base: 40267f117bc5341de8e2604688e4294228adca385571ec2156d98e015da5523e99dbcc2ab70b40969d145e0d89d2d30123507a4b38edc8dc5fde873818783825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
